import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import * as ExifReader from 'exifreader';
import type { ExpandedTags } from 'exifreader';

type Verdict = 'ai' | 'suspicious' | 'none';
type EvidenceKind = 'c2pa' | 'aigc' | 'provider' | 'metadata';

interface ImageDimensions {
    width: number;
    height: number;
}

interface MetadataRow {
    group: string;
    groupLabel: string;
    name: string;
    value: string;
}

interface EvidenceItem {
    kind: EvidenceKind;
    title: string;
    detail: string;
    weight: number;
}

interface ProviderGuess {
    name: string;
    confidence: '高' | '中' | '低';
    reason: string;
    score: number;
}

interface TermHit {
    label: string;
    term: string;
    offsets: number[];
}

interface DetectionResult {
    verdict: Verdict;
    score: number;
    label: string;
    summary: string;
    provider: ProviderGuess | null;
    evidence: EvidenceItem[];
    termHits: TermHit[];
    metadataRows: MetadataRow[];
    file: {
        name: string;
        type: string;
        size: number;
        detectedType: string;
        lastModified: number;
    };
    dimensions: ImageDimensions | null;
    reportJson: string;
}

const GROUP_LABELS: Record<string, string> = {
    file: '文件',
    jfif: 'JFIF',
    pngFile: 'PNG 文件',
    pngText: 'PNG 文本',
    png: 'PNG',
    exif: 'EXIF',
    iptc: 'IPTC',
    xmp: 'XMP',
    icc: 'ICC 色彩',
    riff: 'RIFF/WebP',
    gif: 'GIF',
    Thumbnail: '缩略图',
    gps: 'GPS',
    photoshop: 'Photoshop',
    makerNotes: '厂商 MakerNote',
    composite: '计算字段',
};

const TERM_GROUPS = [
    {
        label: 'C2PA',
        terms: ['c2pa', 'C2PA', 'jumb', 'JUMBF', 'Content Credentials', 'contentcredentials', 'manifest-store'],
    },
    {
        label: 'OpenAI',
        terms: ['OpenAI', 'openai', 'GPT-image', 'GPT Image', 'gpt-image', 'ChatGPT', 'DALL-E', 'DALL·E'],
    },
    {
        label: 'C2PA AI Source',
        terms: [
            'trainedAlgorithmicMedia',
            'compositeWithTrainedAlgorithmicMedia',
            'digitalSourceType',
            'createdWithAI',
            'generativeAI',
        ],
    },
    {
        label: 'Nano-Banana-2',
        terms: ['Nano Banana', 'Nano-Banana', 'nano-banana', 'Gemini', 'gemini', 'Google'],
    },
    {
        label: 'AIGC',
        terms: ['AIGC', 'aigc', 'AI Generated', 'AI-generated', 'Generated by AI', 'synthetic media'],
    },
    {
        label: 'Doubao',
        terms: ['Doubao', 'doubao', '豆包', 'ByteDance', 'bytedance', '字节跳动', 'Seedream', 'seedream'],
    },
    {
        label: 'Tencent Hunyuan',
        terms: ['Hunyuan', 'hunyuan', '混元', 'Tencent', 'tencent', '腾讯'],
    },
    {
        label: 'Ali Wanxiang',
        terms: ['Wanxiang', 'wanxiang', '万相', 'Tongyi', 'tongyi', '通义', 'Alibaba', 'alibaba', '阿里'],
    },
];

const MAX_OFFSETS = 6;
const MAX_VALUE_LENGTH = 3000;

const encoder = new TextEncoder();

const formatBytes = (bytes: number) => {
    if (bytes === 0) return '0 B';
    const units = ['B', 'KB', 'MB', 'GB'];
    const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
    const value = bytes / 1024 ** index;
    return `${value >= 100 ? Math.round(value) : value.toFixed(value >= 10 ? 1 : 2)} ${units[index]}`;
};

const formatDateTime = (time: number) => {
    if (!time) return '未知';
    return new Intl.DateTimeFormat('zh-CN', {
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
    }).format(new Date(time));
};

const readAscii = (bytes: Uint8Array, start: number, end: number) => {
    let output = '';
    for (let index = Math.max(0, start); index < Math.min(end, bytes.length); index += 1) {
        const code = bytes[index];
        output += code >= 32 && code <= 126 ? String.fromCharCode(code) : '.';
    }
    return output;
};

const detectImageType = (bytes: Uint8Array, fallbackType: string) => {
    if (bytes.length >= 12 && readAscii(bytes, 0, 4) === 'RIFF' && readAscii(bytes, 8, 12) === 'WEBP') return 'WebP';
    if (bytes.length >= 8 && bytes[0] === 0x89 && readAscii(bytes, 1, 4) === 'PNG') return 'PNG';
    if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return 'JPEG';
    if (bytes.length >= 6 && (readAscii(bytes, 0, 6) === 'GIF87a' || readAscii(bytes, 0, 6) === 'GIF89a')) return 'GIF';
    if (bytes.length >= 12 && readAscii(bytes, 4, 8) === 'ftyp') return readAscii(bytes, 8, 12).trim() || 'ISO BMFF';
    if (bytes.length >= 2 && readAscii(bytes, 0, 2) === 'BM') return 'BMP';
    return fallbackType || '未知';
};

const findBytes = (bytes: Uint8Array, pattern: Uint8Array, maxCount = MAX_OFFSETS) => {
    const offsets: number[] = [];
    if (!pattern.length || pattern.length > bytes.length) return offsets;

    for (let index = 0; index <= bytes.length - pattern.length; index += 1) {
        let matched = true;
        for (let patternIndex = 0; patternIndex < pattern.length; patternIndex += 1) {
            if (bytes[index + patternIndex] !== pattern[patternIndex]) {
                matched = false;
                break;
            }
        }
        if (matched) {
            offsets.push(index);
            if (offsets.length >= maxCount) break;
        }
    }

    return offsets;
};

const scanBinaryTerms = (arrayBuffer: ArrayBuffer) => {
    const bytes = new Uint8Array(arrayBuffer);

    return TERM_GROUPS.flatMap(group => (
        group.terms
            .map(term => ({
                label: group.label,
                term,
                offsets: findBytes(bytes, encoder.encode(term)),
            }))
            .filter(hit => hit.offsets.length > 0)
    ));
};

const truncateValue = (value: string) => {
    if (value.length <= MAX_VALUE_LENGTH) return value;
    return `${value.slice(0, MAX_VALUE_LENGTH)}\n... 已截断 ${value.length - MAX_VALUE_LENGTH} 个字符`;
};

const safeStringify = (value: unknown) => {
    try {
        return JSON.stringify(value, (_key, item) => {
            if (item instanceof ArrayBuffer) return `[ArrayBuffer ${formatBytes(item.byteLength)}]`;
            if (ArrayBuffer.isView(item)) return `[${item.constructor.name} ${formatBytes(item.byteLength)}]`;
            if (typeof item === 'bigint') return item.toString();
            if (typeof item === 'string') return truncateValue(item);
            return item;
        }, 2);
    } catch {
        return String(value);
    }
};

const valueToText = (value: unknown): string => {
    if (value === null || value === undefined) return '';
    if (typeof value === 'string') return truncateValue(value);
    if (typeof value === 'number' || typeof value === 'boolean' || typeof value === 'bigint') return String(value);
    if (value instanceof ArrayBuffer) return `[ArrayBuffer ${formatBytes(value.byteLength)}]`;
    if (ArrayBuffer.isView(value)) return `[${value.constructor.name} ${formatBytes(value.byteLength)}]`;
    if (Array.isArray(value)) return safeStringify(value.length > 24 ? [...value.slice(0, 24), `... ${value.length - 24} more`] : value);
    return safeStringify(value);
};

const tagToText = (tag: unknown) => {
    if (!tag || typeof tag !== 'object') return valueToText(tag);
    const candidate = tag as { description?: unknown; value?: unknown };
    const description = valueToText(candidate.description);
    return description || valueToText(candidate.value ?? tag);
};

const flattenMetadata = (tags: ExpandedTags): MetadataRow[] => (
    Object.entries(tags).flatMap(([group, groupValue]) => {
        if (!groupValue || typeof groupValue !== 'object') return [];

        return Object.entries(groupValue as Record<string, unknown>)
            .map(([name, value]) => ({
                group,
                groupLabel: GROUP_LABELS[group] ?? group,
                name,
                value: tagToText(value),
            }))
            .filter(row => row.value.length > 0 && row.name.toLowerCase() !== 'image' && row.name.toLowerCase() !== 'base64');
    })
);

const loadImageDimensions = (url: string) => new Promise<ImageDimensions | null>((resolve) => {
    const image = new Image();
    image.onload = () => resolve({ width: image.naturalWidth, height: image.naturalHeight });
    image.onerror = () => resolve(null);
    image.src = url;
});

const rowContains = (row: MetadataRow, terms: string[]) => {
    const haystack = `${row.group} ${row.name} ${row.value}`.toLowerCase();
    return terms.some(term => haystack.includes(term.toLowerCase()));
};

const hasHit = (hits: TermHit[], label: string) => hits.some(hit => hit.label === label);

const hasAigcInGroup = (rows: MetadataRow[], group: string) => (
    rows.some(row => row.group.toLowerCase() === group && rowContains(row, ['AIGC', 'AI Generated', 'Generated by AI']))
);

const findAuthorAigcRow = (rows: MetadataRow[]) => rows.find(row => (
    /author|artist|creator|by-line|dc:creator|photoshop:authorsposition/i.test(row.name)
    && rowContains(row, ['AIGC'])
));

const findProviderRows = (rows: MetadataRow[], terms: string[]) => rows.filter(row => rowContains(row, terms));

const addEvidence = (
    evidence: EvidenceItem[],
    kind: EvidenceKind,
    title: string,
    detail: string,
    weight: number
) => {
    evidence.push({ kind, title, detail, weight });
};

const chooseProvider = (candidates: ProviderGuess[]) => {
    if (candidates.length === 0) return null;
    return [...candidates].sort((a, b) => b.score - a.score)[0];
};

const buildDetectionResult = (
    file: File,
    dimensions: ImageDimensions | null,
    detectedType: string,
    metadataRows: MetadataRow[],
    termHits: TermHit[]
): Omit<DetectionResult, 'file' | 'dimensions' | 'reportJson'> => {
    const evidence: EvidenceItem[] = [];
    const providers: ProviderGuess[] = [];
    const c2paFound = hasHit(termHits, 'C2PA');
    const openAiFound = hasHit(termHits, 'OpenAI') || findProviderRows(metadataRows, ['OpenAI', 'GPT-image', 'ChatGPT']).length > 0;
    const c2paAiSourceFound = hasHit(termHits, 'C2PA AI Source') || findProviderRows(metadataRows, ['trainedAlgorithmicMedia', 'digitalSourceType', 'createdWithAI']).length > 0;
    const nanoFound = hasHit(termHits, 'Nano-Banana-2') || findProviderRows(metadataRows, ['Nano Banana', 'Nano-Banana', 'Gemini', 'Google']).length > 0;
    const xmpAigcFound = hasAigcInGroup(metadataRows, 'xmp');
    const exifAigcFound = hasAigcInGroup(metadataRows, 'exif');
    const authorAigcRow = findAuthorAigcRow(metadataRows);
    const metadataAigcRows = metadataRows.filter(row => rowContains(row, ['AIGC', 'AI Generated', 'Generated by AI']));
    const binaryAigcFound = hasHit(termHits, 'AIGC');

    if (c2paFound && openAiFound) {
        addEvidence(evidence, 'provider', 'OpenAI C2PA Manifest', '检测到 C2PA/JUMBF 线索，并命中 OpenAI/GPT-image/ChatGPT 字符串。', 96);
        providers.push({
            name: 'OpenAI / GPT-image-2',
            confidence: '高',
            reason: 'C2PA Manifest 中出现 OpenAI 相关字符串',
            score: 96,
        });
    } else if (c2paFound && c2paAiSourceFound) {
        addEvidence(evidence, 'c2pa', 'C2PA AI 来源声明', '检测到 C2PA 结构，并命中 trainedAlgorithmicMedia / digitalSourceType 等 AI 来源字段。', 88);
    } else if (c2paFound) {
        addEvidence(evidence, 'c2pa', 'C2PA/JUMBF 线索', '图片中存在 C2PA 或 JUMBF 字符串。它可用于 AI 生成来源声明，也可能来自其他 provenance 工具。', 58);
    }

    if (c2paFound && nanoFound) {
        addEvidence(evidence, 'provider', 'Nano-Banana-2 / Google 系线索', '检测到 C2PA，同时命中 Nano Banana、Gemini 或 Google 相关字符串。', 82);
        providers.push({
            name: 'Nano-Banana-2 / Google 系生成器',
            confidence: '中',
            reason: 'C2PA 与 Nano Banana / Gemini / Google 字符串同时出现',
            score: 82,
        });
    }

    if (xmpAigcFound) {
        addEvidence(evidence, 'aigc', 'XMP AIGC 标识', 'XMP metadata 中出现 AIGC/AI Generated 字符串，符合豆包类图片的标记特征。', 88);
        providers.push({
            name: '豆包特征',
            confidence: '中',
            reason: 'AIGC 标识位于 XMP metadata',
            score: 78,
        });
    }

    if (exifAigcFound) {
        addEvidence(evidence, 'aigc', 'EXIF AIGC 标识', 'EXIF metadata 中出现 AIGC/AI Generated 字符串，符合腾讯混元类图片的标记特征。', 88);
        providers.push({
            name: '腾讯混元特征',
            confidence: '中',
            reason: 'AIGC 标识位于 EXIF metadata',
            score: 78,
        });
    }

    if (authorAigcRow) {
        addEvidence(evidence, 'aigc', 'Author=AIGC 标识', `${authorAigcRow.groupLabel}.${authorAigcRow.name} 字段中出现 AIGC，符合阿里万相类图片的标记特征。`, 92);
        providers.push({
            name: '阿里万相特征',
            confidence: '中',
            reason: 'Author/Creator 类属性中标记 AIGC',
            score: 84,
        });
    }

    if (!xmpAigcFound && !exifAigcFound && !authorAigcRow && metadataAigcRows.length > 0) {
        addEvidence(evidence, 'aigc', 'Metadata AIGC 字符串', `在 ${metadataAigcRows[0].groupLabel}.${metadataAigcRows[0].name} 等字段中发现 AIGC/AI Generated。`, 78);
    }

    if (binaryAigcFound && metadataAigcRows.length === 0) {
        addEvidence(evidence, 'aigc', '文件内 AIGC 字符串', '在图片二进制内容中发现 AIGC/AI Generated 字符串，但未能定位到结构化 metadata 字段。', 64);
    }

    const doubaoRows = findProviderRows(metadataRows, ['Doubao', '豆包', 'ByteDance', 'Seedream']);
    if (doubaoRows.length > 0 && (metadataAigcRows.length > 0 || binaryAigcFound)) {
        providers.push({
            name: '豆包',
            confidence: '高',
            reason: 'AIGC 标识与豆包/字节相关字符串同时出现',
            score: 90,
        });
    }

    const hunyuanRows = findProviderRows(metadataRows, ['Hunyuan', '混元', 'Tencent', '腾讯']);
    if (hunyuanRows.length > 0 && (metadataAigcRows.length > 0 || binaryAigcFound)) {
        providers.push({
            name: '腾讯混元',
            confidence: '高',
            reason: 'AIGC 标识与混元/腾讯相关字符串同时出现',
            score: 90,
        });
    }

    const wanxiangRows = findProviderRows(metadataRows, ['Wanxiang', '万相', 'Tongyi', '通义', 'Alibaba', '阿里']);
    if (wanxiangRows.length > 0 && (metadataAigcRows.length > 0 || binaryAigcFound || authorAigcRow)) {
        providers.push({
            name: '阿里万相',
            confidence: '高',
            reason: 'AIGC 标识与万相/通义/阿里相关字符串同时出现',
            score: 90,
        });
    }

    const topEvidence = evidence.reduce((max, item) => Math.max(max, item.weight), 0);
    const bonus = Math.min(10, Math.max(0, evidence.length - 1) * 4);
    const score = Math.min(99, topEvidence + bonus);
    const verdict: Verdict = score >= 75 ? 'ai' : score >= 45 ? 'suspicious' : 'none';
    const provider = chooseProvider(providers);

    if (verdict === 'ai') {
        return {
            verdict,
            score,
            label: '检测到 AI 生成标识',
            summary: provider ? `图片内嵌标识显示它很可能由 ${provider.name} 生成。` : '图片内嵌 metadata / 字符串包含明确的 AI 生成线索。',
            provider,
            evidence,
            termHits,
            metadataRows,
        };
    }

    if (verdict === 'suspicious') {
        return {
            verdict,
            score,
            label: '疑似 AI 生成',
            summary: '发现了 provenance 或 AIGC 相关线索，但不足以稳定判定具体生成方。',
            provider,
            evidence,
            termHits,
            metadataRows,
        };
    }

    return {
        verdict,
        score,
        label: '未发现 AI 生成标识',
        summary: '没有在 metadata 或文件内容中发现 C2PA/OpenAI/AIGC 等可识别线索。',
        provider,
        evidence,
        termHits,
        metadataRows,
    };
};

const buildReportJson = (
    result: Omit<DetectionResult, 'file' | 'dimensions' | 'reportJson'>,
    file: DetectionResult['file'],
    dimensions: ImageDimensions | null
) => JSON.stringify({
    verdict: result.verdict,
    score: result.score,
    label: result.label,
    summary: result.summary,
    provider: result.provider,
    evidence: result.evidence,
    termHits: result.termHits.map(hit => ({
        ...hit,
        offsets: hit.offsets.map(offset => `0x${offset.toString(16)}`),
    })),
    file: {
        ...file,
        sizeText: formatBytes(file.size),
        lastModifiedText: formatDateTime(file.lastModified),
    },
    dimensions,
}, null, 2);

const copyText = async (value: string) => {
    if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(value);
        return;
    }

    const textarea = document.createElement('textarea');
    textarea.value = value;
    textarea.setAttribute('readonly', 'true');
    textarea.style.position = 'absolute';
    textarea.style.left = '-9999px';
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
};

const verdictStyle = (verdict: Verdict) => {
    if (verdict === 'ai') {
        return {
            panel: 'border-rose-200 bg-rose-50 text-rose-900 dark:border-rose-900/60 dark:bg-rose-950/30 dark:text-rose-200',
            bar: 'bg-rose-500',
            icon: 'policy',
        };
    }
    if (verdict === 'suspicious') {
        return {
            panel: 'border-amber-200 bg-amber-50 text-amber-900 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-200',
            bar: 'bg-amber-500',
            icon: 'manage_search',
        };
    }
    return {
        panel: 'border-emerald-200 bg-emerald-50 text-emerald-900 dark:border-emerald-900/60 dark:bg-emerald-950/30 dark:text-emerald-200',
        bar: 'bg-emerald-500',
        icon: 'check_circle',
    };
};

const evidenceIcon: Record<EvidenceKind, string> = {
    c2pa: 'verified',
    aigc: 'fingerprint',
    provider: 'business',
    metadata: 'data_object',
};

const AIImageDetectionTool: React.FC = () => {
    const [selectedFile, setSelectedFile] = useState<File | null>(null);
    const [previewUrl, setPreviewUrl] = useState('');
    const [result, setResult] = useState<DetectionResult | null>(null);
    const [isParsing, setIsParsing] = useState(false);
    const [isDragging, setIsDragging] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [copied, setCopied] = useState(false);
    const inputRef = useRef<HTMLInputElement>(null);

    useEffect(() => () => {
        if (previewUrl) URL.revokeObjectURL(previewUrl);
    }, [previewUrl]);

    const reset = useCallback(() => {
        if (previewUrl) URL.revokeObjectURL(previewUrl);
        setSelectedFile(null);
        setPreviewUrl('');
        setResult(null);
        setError(null);
        setCopied(false);
        if (inputRef.current) inputRef.current.value = '';
    }, [previewUrl]);

    const parseFile = useCallback(async (file: File) => {
        if (!file.type.startsWith('image/') && !/\.(jpe?g|png|webp|gif|avif|heic|heif|tiff?|bmp)$/i.test(file.name)) {
            setError('请选择图片文件');
            return;
        }

        if (previewUrl) URL.revokeObjectURL(previewUrl);

        const objectUrl = URL.createObjectURL(file);
        setSelectedFile(file);
        setPreviewUrl(objectUrl);
        setResult(null);
        setError(null);
        setCopied(false);
        setIsParsing(true);

        try {
            const arrayBuffer = await file.arrayBuffer();
            const bytes = new Uint8Array(arrayBuffer);
            const detectedType = detectImageType(bytes, file.type);

            const [dimensions, tags] = await Promise.all([
                loadImageDimensions(objectUrl),
                ExifReader.load(arrayBuffer, {
                    async: true,
                    computed: true,
                    expanded: true,
                    includeUnknown: true,
                }).catch((metadataError: unknown) => {
                    if (metadataError instanceof ExifReader.errors.MetadataMissingError) {
                        return {} as ExpandedTags;
                    }
                    throw metadataError;
                }),
            ]);

            const metadataRows = flattenMetadata(tags);
            const termHits = scanBinaryTerms(arrayBuffer);
            const fileInfo = {
                name: file.name,
                type: file.type,
                size: file.size,
                detectedType,
                lastModified: file.lastModified,
            };
            const baseResult = buildDetectionResult(file, dimensions, detectedType, metadataRows, termHits);
            const reportJson = buildReportJson(baseResult, fileInfo, dimensions);

            setResult({
                ...baseResult,
                file: fileInfo,
                dimensions,
                reportJson,
            });
        } catch (parseError) {
            console.error('AI image detection failed:', parseError);
            setError(parseError instanceof Error ? parseError.message : '图片检测失败');
        } finally {
            setIsParsing(false);
        }
    }, [previewUrl]);

    const handleFileSelect = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0];
        if (file) parseFile(file);
    }, [parseFile]);

    const handleDrop = useCallback((event: React.DragEvent) => {
        event.preventDefault();
        setIsDragging(false);
        const file = event.dataTransfer.files?.[0];
        if (file) parseFile(file);
    }, [parseFile]);

    const handleCopy = useCallback(async () => {
        if (!result) return;
        await copyText(result.reportJson);
        setCopied(true);
        window.setTimeout(() => setCopied(false), 1800);
    }, [result]);

    const hitSummary = useMemo(() => {
        if (!result) return [];
        const labels = Array.from(new Set(result.termHits.map(hit => hit.label)));
        return ['C2PA', 'OpenAI', 'C2PA AI Source', 'AIGC', 'Nano-Banana-2', 'Doubao', 'Tencent Hunyuan', 'Ali Wanxiang']
            .map(label => ({
                label,
                active: labels.includes(label),
            }));
    }, [result]);

    const styles = result ? verdictStyle(result.verdict) : null;

    return (
        <div className="flex w-full flex-col items-center px-4 py-10 sm:px-6 lg:px-8">
            <div className="mb-8 flex w-full max-w-6xl flex-col items-center gap-2 text-center">
                <p className="text-3xl font-black leading-tight tracking-tighter text-gray-900 dark:text-white sm:text-4xl">
                    AI图片检测
                </p>
                <p className="text-base font-normal text-gray-500 dark:text-gray-400">
                    基于 C2PA、OpenAI、AIGC、XMP、EXIF 与 Author 标识判断图片来源
                </p>
            </div>

            <div className="flex w-full max-w-6xl flex-col gap-6">
                {error && (
                    <div className="rounded-lg border border-red-200 bg-red-100 p-4 dark:border-red-800 dark:bg-red-900/50">
                        <p className="text-sm text-red-800 dark:text-red-300">{error}</p>
                    </div>
                )}

                <section className="w-full overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-background-dark">
                    {!result && !isParsing ? (
                        <label
                            className={`m-6 flex cursor-pointer flex-col items-center gap-6 rounded-lg border-2 border-dashed p-8 text-center transition-colors sm:p-14 ${
                                isDragging
                                    ? 'border-primary bg-primary/5'
                                    : 'border-gray-300 hover:border-primary dark:border-gray-700 dark:hover:border-primary'
                            }`}
                            onDragEnter={(event) => {
                                event.preventDefault();
                                setIsDragging(true);
                            }}
                            onDragOver={(event) => event.preventDefault()}
                            onDragLeave={() => setIsDragging(false)}
                            onDrop={handleDrop}
                        >
                            <span className="material-symbols-outlined text-5xl text-gray-400 dark:text-gray-500">
                                policy
                            </span>
                            <div className="flex flex-col items-center gap-2">
                                <p className="text-lg font-bold text-gray-900 dark:text-white">拖拽图片至此</p>
                                <p className="text-sm text-gray-500 dark:text-gray-400">支持 JPG、PNG、WebP、GIF、AVIF、HEIC、TIFF</p>
                            </div>
                            <span className="flex h-10 min-w-[84px] cursor-pointer items-center justify-center overflow-hidden rounded-lg bg-gray-100 px-4 text-sm font-bold text-gray-800 transition-colors hover:bg-gray-200 dark:bg-white/10 dark:text-white dark:hover:bg-white/20">
                                点击选择文件
                            </span>
                            <input
                                ref={inputRef}
                                type="file"
                                accept="image/*,.heic,.heif,.avif,.tif,.tiff"
                                onChange={handleFileSelect}
                                className="hidden"
                            />
                        </label>
                    ) : (
                        <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]">
                            <div className="relative flex flex-col gap-5 border-b border-gray-200 p-6 dark:border-gray-700/50 lg:border-b-0 lg:border-r">
                                <div className="flex items-center justify-between gap-3">
                                    <h3 className="flex items-center gap-2 text-base font-semibold leading-normal text-gray-900 dark:text-white">
                                        <span className="material-symbols-outlined text-xl">image</span>
                                        上传的图片
                                    </h3>
                                    <button
                                        onClick={reset}
                                        className="text-xs text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300"
                                    >
                                        更换图片
                                    </button>
                                </div>

                                <div className="flex min-h-[300px] flex-1 items-center justify-center rounded-lg border border-gray-200 bg-gray-50 p-4 dark:border-gray-700 dark:bg-gray-900/50">
                                    {previewUrl && !isParsing && (
                                        <img
                                            src={previewUrl}
                                            alt="Preview"
                                            className="max-h-[420px] max-w-full object-contain"
                                        />
                                    )}
                                    {isParsing && (
                                        <div className="flex flex-col items-center gap-3 text-gray-500 dark:text-gray-400">
                                            <div className="spinner" style={{ width: '32px', height: '32px', borderWidth: '3px', borderTopColor: '#607AFB' }}></div>
                                            <span className="text-sm">检测中...</span>
                                        </div>
                                    )}
                                </div>

                                {selectedFile && (
                                    <p className="truncate text-center text-xs text-gray-500 dark:text-gray-400">{selectedFile.name}</p>
                                )}

                                {result && (
                                    <div className="grid grid-cols-2 gap-3">
                                        <div className="rounded-lg border border-gray-200 bg-gray-50 p-3 dark:border-gray-700 dark:bg-gray-900/40">
                                            <p className="text-xs text-gray-500 dark:text-gray-400">文件大小</p>
                                            <p className="mt-1 text-sm font-semibold text-gray-900 dark:text-white">{formatBytes(result.file.size)}</p>
                                        </div>
                                        <div className="rounded-lg border border-gray-200 bg-gray-50 p-3 dark:border-gray-700 dark:bg-gray-900/40">
                                            <p className="text-xs text-gray-500 dark:text-gray-400">图片尺寸</p>
                                            <p className="mt-1 text-sm font-semibold text-gray-900 dark:text-white">
                                                {result.dimensions ? `${result.dimensions.width} x ${result.dimensions.height}` : '未读取'}
                                            </p>
                                        </div>
                                        <div className="rounded-lg border border-gray-200 bg-gray-50 p-3 dark:border-gray-700 dark:bg-gray-900/40">
                                            <p className="text-xs text-gray-500 dark:text-gray-400">识别格式</p>
                                            <p className="mt-1 text-sm font-semibold text-gray-900 dark:text-white">{result.file.detectedType}</p>
                                        </div>
                                        <div className="rounded-lg border border-gray-200 bg-gray-50 p-3 dark:border-gray-700 dark:bg-gray-900/40">
                                            <p className="text-xs text-gray-500 dark:text-gray-400">检测分数</p>
                                            <p className="mt-1 text-sm font-semibold text-gray-900 dark:text-white">{result.score}/100</p>
                                        </div>
                                    </div>
                                )}
                            </div>

                            <div className="flex min-h-[560px] flex-col gap-5 bg-gray-50/50 p-6 dark:bg-gray-800/30">
                                {result && styles ? (
                                    <>
                                        <div className={`rounded-lg border p-5 ${styles.panel}`}>
                                            <div className="flex items-start gap-3">
                                                <span className="material-symbols-outlined text-3xl">{styles.icon}</span>
                                                <div className="min-w-0 flex-1">
                                                    <p className="text-xl font-black leading-tight">{result.label}</p>
                                                    <p className="mt-2 text-sm leading-relaxed">{result.summary}</p>
                                                    <div className="mt-4 h-2 overflow-hidden rounded-full bg-white/70 dark:bg-black/20">
                                                        <div className={`h-full ${styles.bar}`} style={{ width: `${Math.max(6, result.score)}%` }}></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                                            <div className="rounded-lg border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900/40">
                                                <p className="text-xs text-gray-500 dark:text-gray-400">生成方判断</p>
                                                <p className="mt-1 text-base font-bold text-gray-900 dark:text-white">
                                                    {result.provider?.name ?? '暂未识别'}
                                                </p>
                                                <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                                                    {result.provider ? `${result.provider.confidence}置信度 · ${result.provider.reason}` : '没有命中足够明确的厂商字符串'}
                                                </p>
                                            </div>
                                            <div className="rounded-lg border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900/40">
                                                <p className="text-xs text-gray-500 dark:text-gray-400">修改时间</p>
                                                <p className="mt-1 text-base font-bold text-gray-900 dark:text-white">{formatDateTime(result.file.lastModified)}</p>
                                                <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">未发现标识不等于图片一定由相机拍摄</p>
                                            </div>
                                        </div>

                                        <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
                                            {hitSummary.map(item => (
                                                <div
                                                    key={item.label}
                                                    className={`rounded-lg border px-3 py-2 text-xs font-semibold ${
                                                        item.active
                                                            ? 'border-primary/30 bg-primary/10 text-primary'
                                                            : 'border-gray-200 bg-white text-gray-400 dark:border-gray-700 dark:bg-gray-900/40 dark:text-gray-500'
                                                    }`}
                                                >
                                                    {item.label}
                                                </div>
                                            ))}
                                        </div>

                                        <div className="flex flex-col gap-3">
                                            <div className="flex items-center justify-between gap-3">
                                                <h3 className="text-base font-bold text-gray-900 dark:text-white">判定证据</h3>
                                                <button
                                                    onClick={handleCopy}
                                                    className="flex h-9 items-center justify-center gap-2 rounded-lg border border-gray-200 bg-white px-3 text-sm font-semibold text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200 dark:hover:bg-gray-800"
                                                >
                                                    <span className="material-symbols-outlined text-lg">{copied ? 'check' : 'content_copy'}</span>
                                                    {copied ? '已复制' : '复制报告'}
                                                </button>
                                            </div>

                                            {result.evidence.length > 0 ? (
                                                <div className="space-y-3">
                                                    {result.evidence.map((item, index) => (
                                                        <div key={`${item.title}-${index}`} className="rounded-lg border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900/40">
                                                            <div className="flex items-start gap-3">
                                                                <span className="material-symbols-outlined text-xl text-primary">{evidenceIcon[item.kind]}</span>
                                                                <div className="min-w-0 flex-1">
                                                                    <div className="flex flex-wrap items-center gap-2">
                                                                        <p className="text-sm font-bold text-gray-900 dark:text-white">{item.title}</p>
                                                                        <span className="rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-500 dark:bg-gray-800 dark:text-gray-400">
                                                                            +{item.weight}
                                                                        </span>
                                                                    </div>
                                                                    <p className="mt-1 text-xs leading-relaxed text-gray-500 dark:text-gray-400">{item.detail}</p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    ))}
                                                </div>
                                            ) : (
                                                <div className="rounded-lg border border-gray-200 bg-white p-6 text-center dark:border-gray-700 dark:bg-gray-900/40">
                                                    <p className="text-sm text-gray-500 dark:text-gray-400">没有发现可用于判断 AI 来源的 metadata 证据</p>
                                                </div>
                                            )}
                                        </div>

                                        {result.termHits.length > 0 && (
                                            <details className="rounded-lg border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900/40">
                                                <summary className="cursor-pointer text-sm font-bold text-gray-900 dark:text-white">字符串命中位置</summary>
                                                <div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-2">
                                                    {result.termHits.map((hit, index) => (
                                                        <div key={`${hit.label}-${hit.term}-${index}`} className="rounded-lg bg-gray-50 p-3 dark:bg-gray-800/60">
                                                            <p className="text-xs font-bold text-gray-700 dark:text-gray-200">{hit.label} · {hit.term}</p>
                                                            <p className="mt-1 break-words text-xs text-gray-500 dark:text-gray-400">
                                                                {hit.offsets.map(offset => `0x${offset.toString(16)}`).join(', ')}
                                                            </p>
                                                        </div>
                                                    ))}
                                                </div>
                                            </details>
                                        )}
                                    </>
                                ) : (
                                    <div className="flex flex-1 items-center justify-center">
                                        <div className="flex flex-col items-center gap-3 text-gray-500 dark:text-gray-400">
                                            <div className="spinner" style={{ width: '32px', height: '32px', borderWidth: '3px', borderTopColor: '#607AFB' }}></div>
                                            <p className="text-sm">正在分析图片来源...</p>
                                        </div>
                                    </div>
                                )}
                            </div>
                        </div>
                    )}
                </section>
            </div>
        </div>
    );
};

export default AIImageDetectionTool;
